In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False
f_path = "/users/hong/Documents/Library/Fonts/malgun.ttf"
font_name = font_manager.FontProperties(fname=f_path).get_name()
rc('font', family=font_name)

In [4]:
filename='C:\deep\\foodtruck/KoreaFoodTruck.csv'

In [5]:
foodtruck_data=pd.read_csv(filename, encoding='utf8', index_col=0, header=0)

In [6]:
ft_tbl = pd.DataFrame(foodtruck_data)
ft_locs = pd.DataFrame(ft_tbl[['사업장명','소재지전체주소','도로명전체주소']])

In [7]:
ft_locs.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>사업장명</th>
      <th>소재지전체주소</th>
      <th>도로명전체주소</th>
    </tr>
    <tr>
      <th>번호</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>유리성휴게점</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>천제 푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
    </tr>
    <tr>
      <th>3</th>
      <td>중문푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
    </tr>
    <tr>
      <th>4</th>
      <td>스트린런치푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>팜랜드 푸드트럭</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
      <td>경기도 안성시 공도읍 대신두길 28</td>
    </tr>
  </tbody>
</table>
</div>

In [14]:
ft_locs = ft_locs.drop_duplicates()
ft_locs.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>사업장명</th>
      <th>소재지전체주소</th>
      <th>도로명전체주소</th>
    </tr>
    <tr>
      <th>번호</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>유리성휴게점</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>천제 푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
    </tr>
    <tr>
      <th>3</th>
      <td>중문푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
    </tr>
    <tr>
      <th>4</th>
      <td>스트린런치푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>팜랜드 푸드트럭</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
      <td>경기도 안성시 공도읍 대신두길 28</td>
    </tr>
  </tbody>
</table>
</div>

In [15]:
ft_locs = ft_locs.dropna(how="all")
ft_locs.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>사업장명</th>
      <th>소재지전체주소</th>
      <th>도로명전체주소</th>
    </tr>
    <tr>
      <th>번호</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>유리성휴게점</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>천제 푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
    </tr>
    <tr>
      <th>3</th>
      <td>중문푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
    </tr>
    <tr>
      <th>4</th>
      <td>스트린런치푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>팜랜드 푸드트럭</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
      <td>경기도 안성시 공도읍 대신두길 28</td>
    </tr>
  </tbody>
</table>
</div>

In [16]:
ft_locs["정리한전체주소"] =ft_locs['소재지전체주소']
ft_locs.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>사업장명</th>
      <th>소재지전체주소</th>
      <th>도로명전체주소</th>
      <th>정리한전체주소</th>
    </tr>
    <tr>
      <th>번호</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>유리성휴게점</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
      <td>NaN</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
    </tr>
    <tr>
      <th>2</th>
      <td>천제 푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
    </tr>
    <tr>
      <th>3</th>
      <td>중문푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
    </tr>
    <tr>
      <th>4</th>
      <td>스트린런치푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
      <td>NaN</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
    </tr>
    <tr>
      <th>5</th>
      <td>팜랜드 푸드트럭</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
      <td>경기도 안성시 공도읍 대신두길 28</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
    </tr>
  </tbody>
</table>
</div>

In [17]:
ft_locs['정리한전체주소'].fillna(ft_locs['도로명전체주소'])
ft_locs.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>사업장명</th>
      <th>소재지전체주소</th>
      <th>도로명전체주소</th>
      <th>정리한전체주소</th>
    </tr>
    <tr>
      <th>번호</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>유리성휴게점</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
      <td>NaN</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
    </tr>
    <tr>
      <th>2</th>
      <td>천제 푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
    </tr>
    <tr>
      <th>3</th>
      <td>중문푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
      <td>제주특별자치도 서귀포시 천제연로 132 (중문동)</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
    </tr>
    <tr>
      <th>4</th>
      <td>스트린런치푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
      <td>NaN</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
    </tr>
    <tr>
      <th>5</th>
      <td>팜랜드 푸드트럭</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
      <td>경기도 안성시 공도읍 대신두길 28</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
    </tr>
  </tbody>
</table>
</div>

In [18]:
ft_locs = pd.DataFrame(ft_locs[['사업장명','정리한전체주소']])
ft_locs = ft_locs.dropna(subset=['정리한전체주소'], how='any')

In [19]:
ft_locs.head(n=15)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>사업장명</th>
      <th>정리한전체주소</th>
    </tr>
    <tr>
      <th>번호</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>유리성휴게점</td>
      <td>제주특별자치도 서귀포시 색달동 2950-23번지</td>
    </tr>
    <tr>
      <th>2</th>
      <td>천제 푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
    </tr>
    <tr>
      <th>3</th>
      <td>중문푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2232번지</td>
    </tr>
    <tr>
      <th>4</th>
      <td>스트린런치푸드트럭</td>
      <td>제주특별자치도 서귀포시 중문동 2503번지</td>
    </tr>
    <tr>
      <th>5</th>
      <td>팜랜드 푸드트럭</td>
      <td>경기도 안성시 공도읍 신두리 451번지</td>
    </tr>
    <tr>
      <th>6</th>
      <td>나사트레일러커피</td>
      <td>경기도 화성시 봉담읍 하가등리 107-1번지 화성그린환경센터 주민편익시설 내</td>
    </tr>
    <tr>
      <th>7</th>
      <td>시현이네(푸드트럭)</td>
      <td>경기도 남양주시 이패동 산 87번지 남양주종합운동장내푸드트럭/실내체육관 정문광장 오른쪽</td>
    </tr>
    <tr>
      <th>8</th>
      <td>푸드트럭(악양둑방)</td>
      <td>경상남도 함안군 법수면 윤외리 104-2번지 악양 둑방 내</td>
    </tr>
    <tr>
      <th>9</th>
      <td>부여커피푸드트럭</td>
      <td>충청남도 부여군 규암면 반산리 172번지</td>
    </tr>
    <tr>
      <th>10</th>
      <td>어바웃커피</td>
      <td>대전광역시 유성구 봉명동 700번지 갑천변</td>
    </tr>
    <tr>
      <th>11</th>
      <td>경천대 푸드트럭 휴게소</td>
      <td>경상북도 상주시 사벌면 삼덕리 3-3번지</td>
    </tr>
    <tr>
      <th>12</th>
      <td>쉼터작은공간</td>
      <td>인천광역시 계양구 평동 23-12번지 경인아라뱃길푸드트럭 일반존I(인천) 벌말교7</td>
    </tr>
    <tr>
      <th>13</th>
      <td>호끌락</td>
      <td>제주특별자치도 제주시 건입동 505-2번지 일원</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Cafe solo(카페솔로)</td>
      <td>인천광역시 서구 시천동 119-4번지 시천교8</td>
    </tr>
    <tr>
      <th>15</th>
      <td>브라움카페</td>
      <td>대구광역시 중구 대봉동 0214-0031번지 신천둔치 푸드트럭 제2호</td>
    </tr>
  </tbody>
</table>
</div>

In [20]:
ft_locs_cut = pd.DataFrame(ft_locs['정리한전체주소'].apply(lambda v: v.split()[:2]).tolist(),
                        columns=('d1', 'd2'))

In [21]:
d2_aliases = """연기면:세종특별자치시 금남면:세종특별자치시 조치원읍:세종특별자치시 어진동:세종특별자치시 한솔동:세종특별자치시 아름동:세종특별자치시"""

In [23]:
d2_aliases = dict(aliasset.split(':') for aliasset in d2_aliases.split())

In [24]:
ft_locs_cut['d2'] = ft_locs_cut['d2'].apply(lambda v: d2_aliases.get(v, v))

In [25]:
ft_locs_cut['d2'].unique()

array(['서귀포시', '안성시', '화성시', '남양주시', '함안군', '부여군', '유성구', '상주시', '계양구',
       '제주시', '서구', '중구', '영등포구', '평창군', '춘천시', '마포구', '동구', '성동구', '수원시',
       '사천시', '세종특별자치시', '고흥군', '수성구', '남해군', '안양시', '평택시', '대덕구', '칠곡군',
       '북구', '서초구', '종로구', '공주시', '아산시', '부산진구', '금산군', '사상구', '남구',
       '안산시', '부평구', '양평군', '금천구', '해운대구', '양주시', '완도군', '거창군', '고양시',
       '보성군', '의성군', '김해시', '기장군', '강남구', '강릉시', '송파구', '통영시', '강화군',
       '동해시', '가평군', '광진구', '강서구', '양산시', '의왕시', '과천시', '양천구', '성남시',
       '함양군', '창녕군', '청주시', '용인시', '신안군', '인제군', '홍천군', '오산시', '청양군',
       '당진시', '하동군', '은평구', '의령군', '부천시', '동작구', '김포시', '횡성군', '경주시',
       '군산시', '의정부시', '밀양시', '문경시', '충주시', '천안시', '부안군', '포항시', '광주시',
       '달서구', '익산시', '이천시', '남동구', '광산구', '강동구', '중랑구', '구로구', '연천군',
       '파주시', '진주시', '창원시', '도봉구', '거제시', '경산시', '연제구', '서대문구', '장흥군',
       '하남시', '금정구', '관악구', '연수구', '동두천시', '태안군', '양양군', '예산군', '사하구',
       '동래구', '구미시', '진천군', '철원군', '화순군', '노원구', '김제시', '고창군', '고성군',
       '여주시', '정선군', '광명시', '영도구', '영덕군', '괴산군', '삼척시', '원주시', '전주시',
       '합천군', '무안군', '울주군', '시흥시', '군포시', '강북구', '달성군', '산청군', '미추홀구',
       '양구군', '서천군', '남원시', '함평군', '음성군', '제천시', '여수시'], dtype=object)

In [26]:
F = ft_locs_cut.apply(lambda r: r['d1'] + ' '+ r['d2'], axis=1).value_counts()
F.head()

서울특별시 영등포구    137
서울특별시 서초구     106
서울특별시 중구       80
경기도 수원시        46
경상남도 김해시       33
dtype: int64